#!/bin/bash

if [ "x$1" = "x" ] ; then
  tl="$HOME/Development/TeX/texlive.git"
else 
  tl="$1"
fi


if [ ! -d "$tl/Master/texmf-dist/scripts/tlcockpit" ] ; then
  echo "Cannot find $tl/Master/texmf-dist/scripts/tlcockpit, exiting!" >&2
  exit 1
fi

# update source files
mkdir -p "$tl/Master/texmf-dist/source/support/tlcockpit"
rm -rf "$tl/Master/texmf-dist/source/support/tlcockpit"/*
git archive --format=tar HEAD | (cd "$tl/Master/texmf-dist/source/support/tlcockpit" && tar xf -)
rm -rf "$tl/Master/texmf-dist/source/support/tlcockpit"/screenshots
rm -rf "$tl/Master/texmf-dist/source/support/tlcockpit"/README.md
rm -rf "$tl/Master/texmf-dist/source/support/tlcockpit"/NEWS
rm -rf "$tl/Master/texmf-dist/source/support/tlcockpit"/LICENSE
rm -rf "$tl/Master/texmf-dist/source/support/tlcockpit"/jar
rm -rf "$tl/Master/texmf-dist/source/support/tlcockpit"/scripts
rm -rf "$tl/Master/texmf-dist/source/support/tlcockpit"/logo


mkdir -p "$tl/Master/texmf-dist/doc/support/tlcockpit"
rm -rf "$tl/Master/texmf-dist/doc/support/tlcockpit"/*
cp README.md NEWS LICENSE "$tl/Master/texmf-dist/doc/support/tlcockpit/"
cp -a screenshots "$tl/Master/texmf-dist/doc/support/tlcockpit/"


# build deployment jar
if [ ! -r jar/tlcockpit.jar ] ; then
  echo "Rebuilding tlcockpit assembly"
  sbt assembly
fi
cp jar/tlcockpit.jar "$tl/Master/texmf-dist/scripts/tlcockpit/tlcockpit.jar"

# update bin scripts
for i in "$tl"/Master/bin/* ; do
  if [ -d "$i" ] ; then
    bn=`basename "$i"`
    if [ $bn = win32 ] ; then
      cp "$i/wrunscript.exe" "$i/tlcockpit.exe"
    else
      if [ -x "$i/pdftex" ] ; then
        ln -sf ../../texmf-dist/scripts/tlcockpit/tlcockpit-runner.sh "$i/tlcockpit"
      fi
    fi
  fi
done

